### ISSUE TITLE
User::where does not exist

### ISSUE THREAD

**Issue by bajki** [derheyne/laravel-macroable-models#1]
Hi, when i extend User model with MacroableModel i can't user create, update, where.

BadMethodCallException
Method Modules\User\Entities\User::create does not exist.

Thanks

**Comment by derheyne** [comment]
Hey bajki,

thank you for bringing this issue to my attention! In the latest release [v0.2.0](https://github.com/derheyne/laravel-macroable-models/releases/tag/0.2.0) this problem is fixed, at least from my testing.

If you bump into some more problems don't hesitate to let me know.
